"""Aggregated NPU kernels migrated by the conductor pipeline.

Re-exports the integrated per-function kernel modules produced for argmax.
Generated by integrate_kernel.py; edit the per-function modules instead.
"""

from ._argreduce_kernel import _argreduce_kernel

__all__ = [
    "_argreduce_kernel",
]
