"""Aggregated NPU kernels migrated by the conductor pipeline.

Re-exports the integrated per-function kernel modules produced for multi_head_attention.
Generated by integrate_kernel.py; edit the per-function modules instead.
"""

from ._gqa_prefill_fwd_kernel import _gqa_prefill_fwd_kernel

__all__ = [
    "_gqa_prefill_fwd_kernel",
]
